## Cơ bản

Tensor là một mảng nhiều chiều, dùng để biểu diễn các vector, matrix với số chiều lớn.

Để bắt đầu, ta có thể sử dụng hàm *arrange* để tạo một vector hàng *x* chứa 12 số nguyên (integer) bắt đầu với 0. Mặc định sử dụng là kiểu số thực (float). Nếu không được khai báo thêm, một tensor mới sẽ được lưu trữ trong bộ nhớ chính và được tính toán bằng CPU.

In [106]:
import numpy as np

x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Chúng ta có thể lấy kích thước (độ dài theo mỗi trục) của tensor bằng cách sử dụng *shape*

In [107]:
x.shape

(12,)

Nếu chúng ta muốn biết tổng số đối tượng trong tensor, ta sử dụng *size*

In [108]:
x.size

12

Để thay đổi kích thước của tensor mà không chỉnh sửa số lượng phần tử hay giá trị của chúng trong tensor, ta có thể sử dụng hàm *invoke*. Ví dụ, ta sẽ tiến hành chuyển đổi tensor x, từ vector hàng với kích thước (12,) thành ma trận với kích thước (3, 4). Tensor mới này sẽ giữ nguyên các giá trị như cũ, nhưng được thay đổi thành một ma trận với 3 hàng và 4 cột. Chú ý rằng *size* vẫn sẽ giữ nguyên khi thay đổi kích thước

In [109]:
X = x.reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Khi thay đổi kích thước của tensor, ta có thể chỉ cần điền kích thước của 1 chiều, và tensor sẽ tự động tính toán kích thước của chiều còn lại.

In [110]:
Z = x.reshape(3, -1)
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Thông thường, khi chúng ta muốn khởi tạo các ma trận với giá trị 0, 1, một hằng số hay một số ngẫu nhiên nào đó. Ta có thể tạo một tensor với tất cả các giá trị bằng 0 và kích thước (2,3,4) như sau:

In [111]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Tương tự, ta có thể tạo tensor với các giá trị bằng 1 với hàm *ones*

In [112]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Thi thoảng, chúng ta sẽ muốn tạo một tensor với các giá trị ngẫu nhiên. Ví dụ, tạo một tensor với kích thước (3,4) và mỗi phần tử được lấy ngẫu nhiên trong một phân phối chuẩn (phân phối Gauss) có giá trị trung bình bằng 0 và độ lệch chuẩn 1.

In [113]:
np.random.normal(0, 1, size=(3,4))

array([[ 0.4796273 , -1.16102102,  0.51239851,  0.12047902],
       [-0.49219532, -0.15533717, -1.44636983,  0.10135458],
       [ 0.50112297,  0.16669015, -1.51933406,  0.23435941]])

Ta cũng có thể sử dụng các giá trị cụ thể để tạo ra tensor bằng cách dùng các Python list. Hàng sẽ tương ứng với trục 0, và cột tương ứng trục 1.

In [114]:
np.array([[1,3,4,5],[6,7,8,9],[2,4,6,8]])

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [2, 4, 6, 8]])

## Các phép tính toán

Các phép toán cơ bản

In [115]:
x = np.array([1,2,3,4])
y = np.array([2,2,2,2])

x + y, x - y, x * y, x / y, x ** y

(array([3, 4, 5, 6]),
 array([-1,  0,  1,  2]),
 array([2, 4, 6, 8]),
 array([0.5, 1. , 1.5, 2. ]),
 array([ 1,  4,  9, 16], dtype=int32))

Chúng ta cũng có thể ghép nhiều tensor với nhau, chỉ cần cung cấp danh sách các tensor và trục để ghép nối. Trục **0** để ghép nối theo hàng, trục **1** để ghép theo cột.

In [116]:
X = np.arange(12).reshape(3,4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([X, Y], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [117]:
np.concatenate([X, Y], axis=1)

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])

Để so sánh từng phần tử trong hai tensor, chúng ta có thể dùng dấu so sánh **==**

In [118]:
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

Để tính tổng các phần tử trong tensor, ta dùng hàm *sum()*

In [119]:
X.sum()

66

## Chỉ số và cắt mảng

Giống như bất kỳ mảng Python khác, các phần tử trong tensor có thể được truy cập bằng chỉ số (index). 

In [120]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Để truy cập phần tử ở hàng thứ r và cột thứ c, ta dùng X[r:c] (lưu ý: chỉ số hàng và cột bắt đầu từ **0**)

In [121]:
X[2,2]

10

Để lấy mảng cuối cùng của X, ta sử dụng X[-1]

In [122]:
X[-1]

array([ 8,  9, 10, 11])

Để lấy ra hai hàng 0 và 1

In [123]:
X[0:2, :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Để lấy ra hai cột 0 và 1

In [124]:
X[:, 0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

Để đảo ngược tensor X

In [125]:
X[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## Tiết kiệm bộ nhớ

Thực hiện các phép tính toán có thể khiến cho một vùng bộ nhớ mới được cấp phát thêm. Ở ví dụ trước, nếu chúng ta viết Y = X + Y, chúng ta sẽ hủy tham chiếu mà tensor Y đang trỏ tới và tham chiếu nó đến một vùng nhớ mới. Ta có thể kiểm chứng điều này bằng hàm *id()* của Python.

In [126]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Điều này có thể dẫn đến những nguyên nhân không mong muốn. May mắn thay, chúng ta có thể thực hiện các phép tính toán *tại chỗ* bằng cách sử dụng ký hiệu [:]. Ví dụ:

In [127]:
z = np.zeros_like(y)
print('id(z): ', id(z))
z[:] = x + y
print('id(z): ', id(z))

id(z):  2834675764240
id(z):  2834675764240


Hoặc chúng ta có thể viết dạng y += x nếu muốn cộng giá trị của y với x

In [128]:
print('id(y): ', id(y))
y += x
print('id(y): ', id(y))

id(y):  2834675810512
id(y):  2834675810512
